title = "Dora Costa"
baseURL = "https://doracosta.info/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Paralimni/Nicosia, Cyprus"
email = "doraspanashi@gmail.com"
favicon = "/favicon.ico"
firstName = "Dora"
lastName = "Costa"
phone = "00 357 99635699"
profileImage = "img/profile.jpg"
showQr = false
showContact = true
sections = ["approach", "services","experience","education", "volunteering","blog"]


[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/doraspanashi/"
name = "LinkedIn"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

