title = "Dora Costa"
baseURL = "https://doracosta.info/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Paralimni/Nicosia, Cyprus"
email = "doraspanashi@gmail.com"
favicon = "/favicon.ico"
firstName = "Dora"
lastName = "Costa"
phone = "00 357 99635699"
profileImage = "img/profile_scaled.jpg"
showQr = false
showContact = false
sections = ["approach", "services","experience","education", "volunteering","blog"]
description="Dora Costa, a counselling psychologist in Paralimni, Cyprus, offers in-person and online sessions. Specializing in CBT, ADHD support, and addiction counselling, she helps individuals, couples, and families build resilience and achieve personal growth."
customCSS = ["css/custom.css"]


[params.google]

[params.google.analytics]
trackerID = "G-12HK6J0N0Z"

[[params.handles]]
link = "https://www.linkedin.com/in/doraspanashi/"
name = "LinkedIn"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

