title = "Dora Costa"
baseURL = "https://doracosta.info/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
address = "Paralimni/Nicosia, Cyprus"
email = "doraspanashi@gmail.com"
favicon = "/favicon.ico"
firstName = "Dora"
lastName = "Costa"
phone = "00 357 99635699"
profileImage = "img/profile_scaled.jpg"
showQr = false
showContact = false
sections = ["approach", "services","experience","education", "volunteering","blog"]
description="Dora Costa, a counselling psychologist in Paralimni, Cyprus, offers in-person and online sessions. Specializing in CBT, ADHD support, and addiction counselling, she helps individuals, couples, and families build resilience and achieve personal growth."
customCSS = ["css/custom.css"]


[params.google]

[params.google.analytics]
trackerID = "G-12HK6J0N0Z"

[[params.handles]]
link = "https://www.linkedin.com/in/doraspanashi/"
name = "LinkedIn"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "Dora Costa"
    [languages.en.params]
      description = "Dora Costa, a counselling psychologist in Paralimni, Cyprus, offers in-person and online sessions. Specializing in CBT, ADHD support, and addiction counselling, she helps individuals, couples, and families build resilience and achieve personal growth."

  [languages.el]
    languageName = "Ελληνικά"
    weight = 2
    title = "Ντόρα Κόστα"
    [languages.el.params]
      description = "Η Ντόρα Κόστα, συμβουλευτική ψυχολόγος στο Παραλίμνι, Κύπρος, προσφέρει συνεδρίες δια ζώσης και διαδικτυακά. Ειδικεύεται στη ΓΣΘ (CBT), στην υποστήριξη για ΔΕΠ-Υ και στη συμβουλευτική εξαρτήσεων, βοηθώντας άτομα, ζευγάρια και οικογένειες να αναπτύξουν ανθεκτικότητα και να επιτύχουν προσωπική ανάπτυξη."

